-- Academias com mais vitórias por finalização
SELECT
    A.NOME   AS ACADEMIA,
    COUNT(*) AS VITORIAS_FINALIZACAO
FROM
         LUTAS L
    JOIN ATLETA   AT ON L.VENCEDOR = AT.ID
    JOIN ACADEMIA A ON AT.ID_ACADEMIA = A.ID_ACADEMIA
WHERE
    L.METODO = 'Finalização'
GROUP BY
    A.NOME
ORDER BY
    VITORIAS_FINALIZACAO DESC;

-- Academia com menor média de tempo das lutas vencidas (Considerando lutas de 5 minutos)
SELECT
    A.NOME AS ACADEMIA,
    ROUND(
        AVG(L.TEMPO_DE_LUTA),
        2
    )      AS MEDIA_TEMPO_VITORIAS
FROM
         LUTAS L
    JOIN ATLETA   AT ON L.VENCEDOR = AT.ID
    JOIN ACADEMIA A ON AT.ID_ACADEMIA = A.ID_ACADEMIA
GROUP BY
    A.NOME
ORDER BY
    MEDIA_TEMPO_VITORIAS ASC;

-- Mestre fundador com alunos mais vitoriosos (proporcionalmente)
SELECT
    A.MESTREFUNDADOR,
    COUNT(L.VENCEDOR)     AS TOTAL_VITORIAS,
    COUNT(DISTINCT AT.ID) AS TOTAL_ATLETAS,
    ROUND(COUNT(L.VENCEDOR) / COUNT(DISTINCT AT.ID),
          2)              AS VITORIAS_POR_ATLETA
FROM
         ACADEMIA A
    JOIN ATLETA AT ON A.ID_ACADEMIA = AT.ID_ACADEMIA
    JOIN LUTAS  L ON AT.ID = L.VENCEDOR
GROUP BY
    A.MESTREFUNDADOR
ORDER BY
    VITORIAS_POR_ATLETA DESC;

-- Top 5 atletas mais vitoriosos
SELECT
    AT.NOME           AS ATLETA,
    A.NOME            AS ACADEMIA,
    COUNT(L.VENCEDOR) AS TOTAL_VITORIAS
FROM
         ATLETA AT
    JOIN LUTAS    L ON AT.ID = L.VENCEDOR
    JOIN ACADEMIA A ON AT.ID_ACADEMIA = A.ID_ACADEMIA
GROUP BY
    AT.NOME,
    A.NOME
ORDER BY
    TOTAL_VITORIAS DESC
FETCH FIRST 5 ROWS ONLY;